site_name: Wander in Mazy's world
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    
  language: en
  palette:
    - scheme: default
      toggle:
       icon: material/toggle-switch
       name: Switch to dark mode
      primary: light green
      accent: teal

    - scheme: slate
      toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to light mode
      primiry: teal
      accent: lime



  